name: GitHub Actions Demo
run-name: CI/CD pipeline
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [24.x]
        steps:
            - uses: actions/checkout@v4
            - name: Starting node.js ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}

            - name: install dependencies
              working-directory: ./client
              run: npm ci

            - name: build app
              working-directory: ./client
              run: npm run build
